apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  labels: 
    app: express
spec:
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: mongo-express
        ports:
        - containerPort: 8081
      env:
      - name: ME_CONFIG_MONGODB_ADMINUSERNAME
        valueFrom:
          secretkeyRef: mongodb-secrets
          key: mongo-username
      - name: ME_CONFIG_MONGODB_ADMINPASSWORD
        valueFrom:
          secretkeyRef: mongodb-secrets
          key: mongo-password
      - name: ME_CONFIG_MONGODB_SERVER
        valueFrom:
          configMapKeyRef: express-configmap
          key: database_name
---
apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: express
  ports: 
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer