apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels: 
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        valueFrom:
          secretkeyRef: mongodb-secrets
          key: mongo-username
      - name: MONGO_INITDB_ROOT_PASSWORD
        valueFrom:
          secretkeyRef: mongodb-secrets
          key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongo
  ports: 
  - protocol: TCP
    port: 27017
    targetPort: 27017